### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Moosems** [mre/pygments-rs#1]
This seems to just be a simple wrapper around the python library. Does this introduce the speed of rust or keep the python speed?

**Comment by mre** [comment]
Hey @Moosems,
this is just a wrapper, yes. It calls into Python, so if anything it is slower than just using Pygments directly. 
The goal was to keep using the Pygments interface for a Rust project. I can't remember which one, and I can't even remember that I even built this library, actually. 😅 
I would recommend to look into https://github.com/birkenfeld/rugments, which is a pure-Rust version, but it is not actively developed either. It might serve as a starting point, though. Be aware, that the Pygments interface is quite large, so it might be easier to look for an alternative highlighter like [syntect](https://github.com/trishume/syntect).
